// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: canvas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CanvasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tracks []*CanvasRequest_Track `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
}

func (x *CanvasRequest) Reset() {
	*x = CanvasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canvas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanvasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasRequest) ProtoMessage() {}

func (x *CanvasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_canvas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasRequest.ProtoReflect.Descriptor instead.
func (*CanvasRequest) Descriptor() ([]byte, []int) {
	return file_canvas_proto_rawDescGZIP(), []int{0}
}

func (x *CanvasRequest) GetTracks() []*CanvasRequest_Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type CanvasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Canvases []*CanvasResponse_Canvas `protobuf:"bytes,1,rep,name=canvases,proto3" json:"canvases,omitempty"`
}

func (x *CanvasResponse) Reset() {
	*x = CanvasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canvas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanvasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasResponse) ProtoMessage() {}

func (x *CanvasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_canvas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasResponse.ProtoReflect.Descriptor instead.
func (*CanvasResponse) Descriptor() ([]byte, []int) {
	return file_canvas_proto_rawDescGZIP(), []int{1}
}

func (x *CanvasResponse) GetCanvases() []*CanvasResponse_Canvas {
	if x != nil {
		return x.Canvases
	}
	return nil
}

type CanvasRequest_Track struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackUri string `protobuf:"bytes,1,opt,name=track_uri,json=trackUri,proto3" json:"track_uri,omitempty"` // spotify:track:5osCClSjGplWagDsJmyivf
}

func (x *CanvasRequest_Track) Reset() {
	*x = CanvasRequest_Track{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canvas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanvasRequest_Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasRequest_Track) ProtoMessage() {}

func (x *CanvasRequest_Track) ProtoReflect() protoreflect.Message {
	mi := &file_canvas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasRequest_Track.ProtoReflect.Descriptor instead.
func (*CanvasRequest_Track) Descriptor() ([]byte, []int) {
	return file_canvas_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CanvasRequest_Track) GetTrackUri() string {
	if x != nil {
		return x.TrackUri
	}
	return ""
}

type CanvasResponse_Canvas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // ef3bc2ac86ba4a39b2cddff19dca884a
	CanvasUrl string                        `protobuf:"bytes,2,opt,name=canvas_url,json=canvasUrl,proto3" json:"canvas_url,omitempty"` // https://canvaz.scdn.co/upload/artist/f.mp4
	TrackUri  string                        `protobuf:"bytes,5,opt,name=track_uri,json=trackUri,proto3" json:"track_uri,omitempty"`    // spotify:track:5osCClSjGplWagDsJmyivf
	Artist    *CanvasResponse_Canvas_Artist `protobuf:"bytes,6,opt,name=artist,proto3" json:"artist,omitempty"`
	OtherId   string                        `protobuf:"bytes,9,opt,name=other_id,json=otherId,proto3" json:"other_id,omitempty"`        // 957a9be5e5c1b9ef1ac1c96b7cebf396
	CanvasUri string                        `protobuf:"bytes,11,opt,name=canvas_uri,json=canvasUri,proto3" json:"canvas_uri,omitempty"` // spotify:canvas:1OuybAWK7XOQMG725ZtFwG
}

func (x *CanvasResponse_Canvas) Reset() {
	*x = CanvasResponse_Canvas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canvas_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanvasResponse_Canvas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasResponse_Canvas) ProtoMessage() {}

func (x *CanvasResponse_Canvas) ProtoReflect() protoreflect.Message {
	mi := &file_canvas_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasResponse_Canvas.ProtoReflect.Descriptor instead.
func (*CanvasResponse_Canvas) Descriptor() ([]byte, []int) {
	return file_canvas_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CanvasResponse_Canvas) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CanvasResponse_Canvas) GetCanvasUrl() string {
	if x != nil {
		return x.CanvasUrl
	}
	return ""
}

func (x *CanvasResponse_Canvas) GetTrackUri() string {
	if x != nil {
		return x.TrackUri
	}
	return ""
}

func (x *CanvasResponse_Canvas) GetArtist() *CanvasResponse_Canvas_Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *CanvasResponse_Canvas) GetOtherId() string {
	if x != nil {
		return x.OtherId
	}
	return ""
}

func (x *CanvasResponse_Canvas) GetCanvasUri() string {
	if x != nil {
		return x.CanvasUri
	}
	return ""
}

type CanvasResponse_Canvas_Artist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtistUri    string `protobuf:"bytes,1,opt,name=artist_uri,json=artistUri,proto3" json:"artist_uri,omitempty"`            // spotify:artist:3E61SnNA9oqKP7hI0K3vZv
	ArtistName   string `protobuf:"bytes,2,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`         // CALVO
	ArtistImgUrl string `protobuf:"bytes,3,opt,name=artist_img_url,json=artistImgUrl,proto3" json:"artist_img_url,omitempty"` // https://i.scdn.co/image/{id}
}

func (x *CanvasResponse_Canvas_Artist) Reset() {
	*x = CanvasResponse_Canvas_Artist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_canvas_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanvasResponse_Canvas_Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanvasResponse_Canvas_Artist) ProtoMessage() {}

func (x *CanvasResponse_Canvas_Artist) ProtoReflect() protoreflect.Message {
	mi := &file_canvas_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanvasResponse_Canvas_Artist.ProtoReflect.Descriptor instead.
func (*CanvasResponse_Canvas_Artist) Descriptor() ([]byte, []int) {
	return file_canvas_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *CanvasResponse_Canvas_Artist) GetArtistUri() string {
	if x != nil {
		return x.ArtistUri
	}
	return ""
}

func (x *CanvasResponse_Canvas_Artist) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *CanvasResponse_Canvas_Artist) GetArtistImgUrl() string {
	if x != nil {
		return x.ArtistImgUrl
	}
	return ""
}

var File_canvas_proto protoreflect.FileDescriptor

var file_canvas_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x61, 0x6e, 0x76, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x52, 0x06, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x1a, 0x24, 0x0a, 0x05, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x75, 0x72, 0x69,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x69,
	0x22, 0x88, 0x03, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x63, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61,
	0x6e, 0x76, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x6e,
	0x76, 0x61, 0x73, 0x52, 0x08, 0x63, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x65, 0x73, 0x1a, 0xbb, 0x02,
	0x0a, 0x06, 0x43, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x76,
	0x61, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61,
	0x6e, 0x76, 0x61, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x5f, 0x75, 0x72, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x55, 0x72, 0x69, 0x12, 0x3b, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x6e,
	0x76, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x61, 0x6e, 0x76,
	0x61, 0x73, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x55, 0x72, 0x69, 0x1a, 0x6e, 0x0a, 0x06, 0x41,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f,
	0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x55, 0x72, 0x69, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f,
	0x69, 0x6d, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x42, 0x2b, 0x5a, 0x29, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x73, 0x66, 0x31, 0x33,
	0x38, 0x32, 0x68, 0x41, 0x63, 0x4b, 0x65, 0x52, 0x2f, 0x43, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x69,
	0x66, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_canvas_proto_rawDescOnce sync.Once
	file_canvas_proto_rawDescData = file_canvas_proto_rawDesc
)

func file_canvas_proto_rawDescGZIP() []byte {
	file_canvas_proto_rawDescOnce.Do(func() {
		file_canvas_proto_rawDescData = protoimpl.X.CompressGZIP(file_canvas_proto_rawDescData)
	})
	return file_canvas_proto_rawDescData
}

var file_canvas_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_canvas_proto_goTypes = []any{
	(*CanvasRequest)(nil),                // 0: proto.CanvasRequest
	(*CanvasResponse)(nil),               // 1: proto.CanvasResponse
	(*CanvasRequest_Track)(nil),          // 2: proto.CanvasRequest.Track
	(*CanvasResponse_Canvas)(nil),        // 3: proto.CanvasResponse.Canvas
	(*CanvasResponse_Canvas_Artist)(nil), // 4: proto.CanvasResponse.Canvas.Artist
}
var file_canvas_proto_depIdxs = []int32{
	2, // 0: proto.CanvasRequest.tracks:type_name -> proto.CanvasRequest.Track
	3, // 1: proto.CanvasResponse.canvases:type_name -> proto.CanvasResponse.Canvas
	4, // 2: proto.CanvasResponse.Canvas.artist:type_name -> proto.CanvasResponse.Canvas.Artist
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_canvas_proto_init() }
func file_canvas_proto_init() {
	if File_canvas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_canvas_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CanvasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canvas_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CanvasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canvas_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CanvasRequest_Track); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canvas_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CanvasResponse_Canvas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_canvas_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CanvasResponse_Canvas_Artist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_canvas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_canvas_proto_goTypes,
		DependencyIndexes: file_canvas_proto_depIdxs,
		MessageInfos:      file_canvas_proto_msgTypes,
	}.Build()
	File_canvas_proto = out.File
	file_canvas_proto_rawDesc = nil
	file_canvas_proto_goTypes = nil
	file_canvas_proto_depIdxs = nil
}
